name: reddit-religion-scraper-env
channels:
  - conda-forge
  - defaults
dependencies:
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - charset-normalizer=3.3.2
  - idna=3.6
  - intel-openmp=2024.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.5.0
  - libffi=3.4.2
  - libhwloc=2.9.3
  - libiconv=1.17
  - liblapack=3.9.0
  - libsqlite=3.45.1
  - libxml2=2.12.5
  - libzlib=1.2.13
  - mkl=2024.0.0
  - numpy=1.26.4
  - openssl=3.2.1
  - pandas=2.2.1
  - pip=24.0
  - praw=7.7.1
  - prawcore=2.4.0
  - pthreads-win32=2.9.1
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0
  - python-dotenv=1.0.1
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - requests=2.31.0
  - setuptools=69.1.1
  - six=1.16.0
  - tbb=2021.11.0
  - tk=8.6.13
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - update_checker=0.18.0
  - urllib3=2.2.1
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - websocket-client=1.7.0
  - wheel=0.42.0
  - win_inet_pton=1.1.0
  - xlsxwriter=3.1.9
  - xz=5.2.6
